# Generated by Django 4.1.2 on 2022-10-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
