# Generated by Django 4.1.2 on 2022-10-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_age_alter_user_country_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channel_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
